package org.rlopez.GUI.models;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import org.rlopez.GUI.dao.ClasseDAO;
import org.rlopez.GUI.dao.VoilierDAO;
import org.rlopez.GUI.dao.ProprietaireDAO;
import org.rlopez.GUI.dao.SerieDAO;

/**
 *
 * @author Richard Lopez
 */
public class MainWindow extends javax.swing.JFrame {
    
    VoilierTableModel vtm;
    
    public MainWindow() {
        
        initComponents();
        
        int serie = ((Serie) comboSerie.getSelectedItem()).getId_serie();
        System.out.println(ClasseDAO.findBy(serie).toArray().length + " " + serie);
        comboClasse.setModel(new javax.swing.DefaultComboBoxModel(ClasseDAO.findBy(serie).toArray()));
        
        initListProprio();
        
        comboClasse.setVisible(false);
        lblClasse.setVisible(false);
        comboProprio.setVisible(false);
        lblPro.setVisible(false);
        btnAddVoilier.setEnabled(false);
    }
    
    public void initListProprio() {
        List<Proprietaire> proprietaires = ProprietaireDAO.findAllProprietaire();
        for (Proprietaire p : proprietaires) {
            comboProprio.addItem(p);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelAddVoilier = new javax.swing.JPanel();
        txtNomVoilier = new javax.swing.JTextField();
        txtNumVoile = new javax.swing.JTextField();
        comboProprio = new javax.swing.JComboBox<>();
        comboClasse = new javax.swing.JComboBox();
        btnAddVoilier = new javax.swing.JButton();
        lblNomVoilier = new javax.swing.JLabel();
        lblNumVoile = new javax.swing.JLabel();
        lblPro = new javax.swing.JLabel();
        lblClasse = new javax.swing.JLabel();
        comboSerie = new javax.swing.JComboBox<>();
        lblSerie = new javax.swing.JLabel();
        lblMsgInfoVoilier = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVoilier = new javax.swing.JTable();
        panelAddPro = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblAddProNom = new javax.swing.JLabel();
        txtAddProNom = new javax.swing.JTextField();
        lblAddProPrenom = new javax.swing.JLabel();
        lblAddProEmail = new javax.swing.JLabel();
        txtAddProPrenom = new javax.swing.JTextField();
        txtAddProEmail = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        lblAddProNumLicence = new javax.swing.JLabel();
        lblAddProAnneeLicence = new javax.swing.JLabel();
        lblAddProNomClub = new javax.swing.JLabel();
        txtAddProNumLicence = new javax.swing.JTextField();
        txtAddProAnneeLicence = new javax.swing.JTextField();
        txtAddProNomClub = new javax.swing.JTextField();
        btnAddPro = new javax.swing.JButton();
        lblMsgInfoProprietaire = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemDelField = new javax.swing.JMenuItem();
        menuItemAboutMe = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelAddVoilier.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajouter un voilier"));

        txtNomVoilier.setToolTipText("Nom du voilier");

        txtNumVoile.setToolTipText("Numéro du voilier sous forme numérique");

        comboProprio.setToolTipText("Choix du propriétaire");
        comboProprio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboProprioActionPerformed(evt);
            }
        });

        comboClasse.setToolTipText("Choix de la classe");
        comboClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClasseActionPerformed(evt);
            }
        });

        btnAddVoilier.setText("Ajouter");
        btnAddVoilier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVoilierActionPerformed(evt);
            }
        });

        lblNomVoilier.setText("Nom du voilier");

        lblNumVoile.setText("Numéro de voile");

        lblPro.setText("Propriétaire");

        lblClasse.setText("Classe");

        List<Serie> series = SerieDAO.findAllSerie();
        for (Serie s : series) {
            comboSerie.addItem(s);
        }
        comboSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSerieActionPerformed(evt);
            }
        });

        lblSerie.setText("Serie");

        jScrollPane1.setViewportView(tblVoilier);
        vtm = new VoilierTableModel(VoilierDAO.findAllVoilier());
        tblVoilier.setModel(vtm);

        javax.swing.GroupLayout panelAddVoilierLayout = new javax.swing.GroupLayout(panelAddVoilier);
        panelAddVoilier.setLayout(panelAddVoilierLayout);
        panelAddVoilierLayout.setHorizontalGroup(
            panelAddVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddVoilierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSerie)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddVoilierLayout.createSequentialGroup()
                        .addComponent(lblMsgInfoVoilier, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddVoilier))
                    .addGroup(panelAddVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAddVoilierLayout.createSequentialGroup()
                            .addComponent(lblPro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboProprio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelAddVoilierLayout.createSequentialGroup()
                            .addGroup(panelAddVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNomVoilier)
                                .addComponent(lblNumVoile)
                                .addComponent(lblClasse))
                            .addGap(30, 30, 30)
                            .addGroup(panelAddVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNomVoilier, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNumVoile, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(comboClasse, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelAddVoilierLayout.setVerticalGroup(
            panelAddVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddVoilierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddVoilierLayout.createSequentialGroup()
                        .addGroup(panelAddVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomVoilier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomVoilier))
                        .addGap(18, 18, 18)
                        .addGroup(panelAddVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNumVoile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumVoile))
                        .addGap(18, 18, 18)
                        .addGroup(panelAddVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSerie))
                        .addGap(18, 18, 18)
                        .addGroup(panelAddVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboClasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClasse))
                        .addGap(18, 18, 18)
                        .addGroup(panelAddVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboProprio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPro))
                        .addGap(30, 30, 30)
                        .addGroup(panelAddVoilierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddVoilier)
                            .addComponent(lblMsgInfoVoilier)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        panelAddPro.setBorder(javax.swing.BorderFactory.createTitledBorder("Ajouter un propriétaire"));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Informations générales"));

        lblAddProNom.setText("Nom");

        lblAddProPrenom.setText("Prénom");

        lblAddProEmail.setText("Email");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddProNom)
                    .addComponent(lblAddProPrenom)
                    .addComponent(lblAddProEmail))
                .addGap(64, 64, 64)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtAddProPrenom)
                    .addComponent(txtAddProEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(txtAddProNom))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProNom)
                    .addComponent(txtAddProNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProPrenom)
                    .addComponent(txtAddProPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProEmail)
                    .addComponent(txtAddProEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Information licence"));

        lblAddProNumLicence.setText("N° de licence");

        lblAddProAnneeLicence.setText("Année de licence");

        lblAddProNomClub.setText("Nom du club");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblAddProNumLicence)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(txtAddProNumLicence, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblAddProNomClub)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAddProNomClub, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(lblAddProAnneeLicence)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAddProAnneeLicence, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProNumLicence)
                    .addComponent(txtAddProNumLicence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProAnneeLicence)
                    .addComponent(txtAddProAnneeLicence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddProNomClub)
                    .addComponent(txtAddProNomClub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnAddPro.setText("Ajouter");
        btnAddPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddProLayout = new javax.swing.GroupLayout(panelAddPro);
        panelAddPro.setLayout(panelAddProLayout);
        panelAddProLayout.setHorizontalGroup(
            panelAddProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddProLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(panelAddProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddProLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddProLayout.createSequentialGroup()
                        .addComponent(lblMsgInfoProprietaire, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addComponent(btnAddPro)))
                .addContainerGap())
        );
        panelAddProLayout.setVerticalGroup(
            panelAddProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddProLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelAddProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPro)
                    .addComponent(lblMsgInfoProprietaire))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAddVoilier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelAddPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAddVoilier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelAddPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Fichier");

        menuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        menuItemExit.setText("Quitter");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edition");

        menuItemDelField.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        menuItemDelField.setText("Effacer tous les champs");
        menuItemDelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDelFieldActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemDelField);

        jMenuBar1.add(jMenu2);

        menuItemAboutMe.setText("?");

        jMenuItem1.setText("À propos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuItemAboutMe.add(jMenuItem1);

        jMenuBar1.add(menuItemAboutMe);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JOptionPane.showMessageDialog(null, "Réalisé par Richard Lopez \nPour l'ECF \"Ajouter un voilier\"");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuItemDelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDelFieldActionPerformed
        txtNomVoilier.setText(null);
        txtNumVoile.setText(null);
        lblClasse.setVisible(false);
        comboProprio.setVisible(false);
        comboClasse.setVisible(false);
        lblPro.setVisible(false);
        btnAddVoilier.setEnabled(false);
        txtAddProNom.setText(null);
        txtAddProPrenom.setText(null);
        txtAddProEmail.setText(null);
        txtAddProNumLicence.setText(null);
        txtAddProAnneeLicence.setText(null);
        txtAddProNomClub.setText(null);

    }//GEN-LAST:event_menuItemDelFieldActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void btnAddProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProActionPerformed
        
        String nomPersonne = txtAddProNom.getText();
        String prenomPersonne = txtAddProPrenom.getText();
        String emailPersonne = txtAddProEmail.getText();
        String numLicence = txtAddProNumLicence.getText();
        String anneeLicence = txtAddProAnneeLicence.getText();
        String nomClub = txtAddProNomClub.getText();
        
        if (nomPersonne.isEmpty() || prenomPersonne.isEmpty() || emailPersonne.isEmpty() || numLicence.isEmpty() || anneeLicence.isEmpty() || nomClub.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Tous les champs sont requis !", "Erreur", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                int strtxtAddProNumLicence = Integer.parseInt(numLicence);
                int strtxtAddProAnneeLicence = Integer.parseInt(anneeLicence);
                Proprietaire pro = new Proprietaire(nomPersonne, prenomPersonne, emailPersonne, strtxtAddProNumLicence, strtxtAddProAnneeLicence, nomClub);
                ProprietaireDAO.insertProprietaire(pro);
                lblMsgInfoProprietaire.setText("Le propriétaire a bien été ajouté.");
                lblMsgInfoProprietaire.setForeground(Color.blue);
                comboProprio.removeAllItems();
                initListProprio();
                txtAddProNom.setText(null);
                txtAddProPrenom.setText(null);
                txtAddProEmail.setText(null);
                txtAddProNumLicence.setText(null);
                txtAddProAnneeLicence.setText(null);
                txtAddProNomClub.setText(null);
                
            } catch (Exception e) {
                lblMsgInfoProprietaire.setText("Erreur !");
                lblMsgInfoProprietaire.setForeground(Color.red);
            }
        }
    }//GEN-LAST:event_btnAddProActionPerformed

    private void comboSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSerieActionPerformed
        int serie = ((Serie) comboSerie.getSelectedItem()).getId_serie();
        comboClasse.setModel(new javax.swing.DefaultComboBoxModel(ClasseDAO.findBy(serie).toArray()));
        
        comboClasse.setVisible(true);
        lblClasse.setVisible(true);
    }//GEN-LAST:event_comboSerieActionPerformed

    private void btnAddVoilierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVoilierActionPerformed
        
        String nomVoilier = txtNomVoilier.getText();
        String numVoile = txtNumVoile.getText();
        Object listeClasse = comboClasse.getSelectedItem();
        Object listeProprio = comboProprio.getSelectedItem();
        
        Classe classe = (Classe) listeClasse;
        Proprietaire proprietaire = (Proprietaire) listeProprio;
        
        if (nomVoilier.isEmpty() || numVoile.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs", "Erreur", JOptionPane.WARNING_MESSAGE);
        } else {
            
            try {
                int strTxtNumVoile = Integer.parseInt(numVoile);
                Voilier voi = new Voilier(nomVoilier, strTxtNumVoile, proprietaire, classe);
                VoilierDAO.insert(voi);
                vtm.addVoilier(voi);
                txtNomVoilier.setText(null);
                txtNumVoile.setText(null);
                comboClasse.setVisible(false);
                lblClasse.setVisible(false);
                comboProprio.setVisible(false);
                lblPro.setVisible(false);
                btnAddVoilier.setEnabled(false);
                lblMsgInfoVoilier.setText("Le voilier a bien été ajouté.");
                lblMsgInfoVoilier.setForeground(Color.blue);
            } catch (Exception e) {
                lblMsgInfoVoilier.setText("Erreur !");
                lblMsgInfoVoilier.setForeground(Color.red);
            }
        }
    }//GEN-LAST:event_btnAddVoilierActionPerformed

    private void comboClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboClasseActionPerformed
        comboProprio.setVisible(true);
        lblPro.setVisible(true);
    }//GEN-LAST:event_comboClasseActionPerformed

    private void comboProprioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProprioActionPerformed
        btnAddVoilier.setEnabled(true);
    }//GEN-LAST:event_comboProprioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPro;
    private javax.swing.JButton btnAddVoilier;
    private javax.swing.JComboBox<Classe> comboClasse;
    private javax.swing.JComboBox<Proprietaire> comboProprio;
    private javax.swing.JComboBox<Serie> comboSerie;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddProAnneeLicence;
    private javax.swing.JLabel lblAddProEmail;
    private javax.swing.JLabel lblAddProNom;
    private javax.swing.JLabel lblAddProNomClub;
    private javax.swing.JLabel lblAddProNumLicence;
    private javax.swing.JLabel lblAddProPrenom;
    private javax.swing.JLabel lblClasse;
    private javax.swing.JLabel lblMsgInfoProprietaire;
    private javax.swing.JLabel lblMsgInfoVoilier;
    private javax.swing.JLabel lblNomVoilier;
    private javax.swing.JLabel lblNumVoile;
    private javax.swing.JLabel lblPro;
    private javax.swing.JLabel lblSerie;
    private javax.swing.JMenu menuItemAboutMe;
    private javax.swing.JMenuItem menuItemDelField;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JPanel panelAddPro;
    private javax.swing.JPanel panelAddVoilier;
    private javax.swing.JTable tblVoilier;
    private javax.swing.JTextField txtAddProAnneeLicence;
    private javax.swing.JTextField txtAddProEmail;
    private javax.swing.JTextField txtAddProNom;
    private javax.swing.JTextField txtAddProNomClub;
    private javax.swing.JTextField txtAddProNumLicence;
    private javax.swing.JTextField txtAddProPrenom;
    private javax.swing.JTextField txtNomVoilier;
    private javax.swing.JTextField txtNumVoile;
    // End of variables declaration//GEN-END:variables
}
